version: '3'

services:
  keycloak:
    image: keycloak:metrics-latest
    build:
      context: .
    command: start-dev --metrics-enabled=true
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - '8080:8080'
