/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.2.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    `java-library`
}

val autoserviceVersion = "1.1.1"
val keycloakVersion = "21.1.2"
val lombokVersion = "1.18.28"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven {
        url = uri("https://repository.jboss.org/nexus/content/repositories/public")
    }
}

dependencies {
    // Use JUnit test framework.
    testImplementation("junit:junit:4.13.2")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.1-jre")

    compileOnly("org.projectlombok:lombok:$lombokVersion")
    annotationProcessor("org.projectlombok:lombok:$lombokVersion")

    compileOnly("com.google.auto.service:auto-service:$autoserviceVersion")
    annotationProcessor("com.google.auto.service:auto-service:$autoserviceVersion")

    compileOnly("io.micrometer:micrometer-core:1.9.4")

    // TODO: is it really needed?
    implementation("org.keycloak:keycloak-quarkus-server:${keycloakVersion}")

    implementation("org.keycloak:keycloak-model-jpa:$keycloakVersion")
    compileOnly("org.keycloak:keycloak-server-spi:$keycloakVersion")
    compileOnly("org.keycloak:keycloak-server-spi-private:$keycloakVersion")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}